version: '3'
services:
  backend_build:
    build:
      context: .
      dockerfile: backend_build.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    command: ./tasks/backend_build.sh
  frontend_build:
    build:
      context: .
      dockerfile: frontend_build.Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: ./tasks/frontend_build.sh
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}
      CFN_STACK_NAME: ${CFN_STACK_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: ./tasks/deploy.sh
