version: '3'
services:
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    environment:
      DYNAMO_URL: http://dynamo:8000
      CFN_STACK_NAME: ${CFN_STACK_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: ./tasks/integration.sh
    depends_on:
      - dynamo
    networks:
      - integration
  dynamo:
    image: amazon/dynamodb-local
    networks:
      - integration
networks:
  integration: