version: '3'
services:
  integration:
    image: node:12
    volumes: 
      - ..:/app
    working_dir: /app
    environment:
      DYNAMO_URL: http://dynamo:8000
    command: ./tasks/integration.sh
    depends_on:
      - dynamo
    networks:
      - integration
  dynamo:
    image: amazon/dynamodb-local
    networks:
      - integration
networks:
  integration: